# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\timu.proto\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\";\n\nQuaternion\x12\t\n\x01i\x18\x01 \x01(\x02\x12\t\n\x01j\x18\x02 \x01(\x02\x12\t\n\x01k\x18\x03 \x01(\x02\x12\x0c\n\x04real\x18\x04 \x01(\x02\"\x9c\x01\n\x07IMUData\x12\x14\n\x0cimu_position\x18\x01 \x01(\t\x12\x1e\n\x0c\x61\x63\x63\x65leration\x18\x02 \x01(\x0b\x32\x08.Vector3\x12\x16\n\x04gyro\x18\x03 \x01(\x0b\x32\x08.Vector3\x12\x15\n\x03mag\x18\x04 \x01(\x0b\x32\x08.Vector3\x12\x19\n\x04quat\x18\x05 \x01(\x0b\x32\x0b.Quaternion\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR3._serialized_start=13
  _VECTOR3._serialized_end=55
  _QUATERNION._serialized_start=57
  _QUATERNION._serialized_end=116
  _IMUDATA._serialized_start=119
  _IMUDATA._serialized_end=275
# @@protoc_insertion_point(module_scope)
